### ISSUE TITLE
bm25_refresh fails

### ISSUE THREAD

**Issue by fa-se** [tensorchord/pg_bestmatch.rs#13]
Hey, thanks for creating this extension!

I am currently in the process of setting this up for BM25, and ran into this issue when trying to execute bm25_refresh:

devdb: public, bm_catalog> SELECT bm25_refresh('publication_abstract_bm25')
[2024-06-29 14:20:33] [42P01] ERROR: relation "bm_catalog.bm25" does not exist
[2024-06-29 14:20:33] Where: PL/pgSQL function bm25_refresh(regclass) line 9 at SQL statement

I believe `bm_catalog.bm25` in the following line should be `bm_catalog.pg_bm25` instead.
https://github.com/tensorchord/pg_bestmatch.rs/blob/419aadf10bc54c59d5712e96de0f9d987b410f5b/src/sql/finalize.sql#L76

**Comment by VoVAllen** [comment]
Thanks for catching the bug! Would you like to submit a PR for this?
